import Foundation

enum L10n {
    static func string(_ key: String, language: AppLanguage) -> String {
        let resolved: AppLanguage
        switch language {
        case .system:
            resolved = Locale.preferredLanguages.first?.hasPrefix("zh") == true
                ? .simplifiedChinese
                : .english
        case .english, .simplifiedChinese:
            resolved = language
        }
        return tables[resolved]?[key] ?? tables[.english]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: [
            "usage": "Usage",
            "five_hour": "5-hour",
            "weekly": "Weekly",
            "usage_unavailable": "Usage unavailable",
            "left": "% left",
            "resets": "Resets",
            "manage": "Manage Accounts",
            "settings": "Settings",
            "quit": "Quit",
            "switch_title": "Switch to %@?",
            "confirm_switch": "Confirm Switch",
            "switch_body": "Codex Desktop will close and reopen. A running Desktop task may be interrupted. Existing CLI sessions stay open; new CLI sessions use the selected account.",
            "switch_impact_desktop": "A running Desktop task may be interrupted",
            "switch_impact_existing_cli": "Existing CLI sessions keep their current account",
            "switch_impact_new_cli": "New CLI sessions use the selected account",
            "switching_title": "Switching account…",
            "cancel": "Cancel",
            "switch": "Switch Account",
            "accounts": "Accounts",
            "back": "Back",
            "add_account": "Add Account",
            "cancel_add_account": "Cancel Adding Account",
            "remove": "Remove",
            "remove_account": "Remove Account",
            "active": "Active",
            "remove_title": "Remove %@?",
            "remove_body": "This removes only the saved local profile from this Mac.",
            "launch_at_login": "Launch at Login",
            "launch_at_login_requires_approval": "Approval is required in System Settings.",
            "launch_at_login_unavailable": "macOS could not find this Login Item.",
            "open_system_settings": "Open System Settings",
            "show_menu_bar_percentage": "Show Percentage in Menu Bar",
            "show_five_hour_usage": "Show 5-hour Usage",
            "show_supported_five_hour_usage": "Show 5-hour Usage for Supported Accounts",
            "account_name_style": "Account Name",
            "show_email": "Email",
            "show_nickname": "Nickname",
            "show_nickname_and_email": "Nickname + Email",
            "edit_nickname": "Edit Remark",
            "set_remark": "Set Remark",
            "nickname": "Remark Name",
            "nickname_hint": "Shown in the menu bar and account list. Leave blank to use the sign-in email.",
            "save": "Save",
            "show_token_activity": "Show Token Usage",
            "show_token_activity_hint": "Shows today's usage for every account and a combined total.",
            "token_scanning": "Scanning local token activity…",
            "token_scanning_short": "Calculating…",
            "today_token": "Today's Tokens",
            "total_token_today": "Today's Total Tokens",
            "token_unavailable_short": "Unavailable",
            "five_hour_reset_notifications": "5-hour Reset Reminders",
            "five_hour_reset_notifications_hint": "Includes a Switch action. Running tasks, or an unknown task state, require confirmation before switching.",
            "notification_permission_denied": "Notifications are not allowed. Enable them for Tiny Codex Switcher in System Settings.",
            "task_switch_active_title": "Codex has a running task",
            "task_switch_active_body": "%@ running task(s) may be interrupted. Switch anyway?",
            "task_switch_unknown_title": "Task status could not be confirmed",
            "task_switch_unknown_body": "Switching may interrupt a Codex task. Switch anyway?",
            "switch_anyway": "Switch Anyway",
            "switch_in_progress": "Another account operation is in progress. Try again when it finishes.",
            "five_hour_reset_notification_title": "5-hour quota reset reached",
            "five_hour_reset_notification_body": "%@ is expected to have refreshed 5-hour quota.",
            "notification_switch_action": "Switch to this account",
            "today": "Today",
            "last_7_days": "7d",
            "last_30_days": "30d",
            "local_model_usage_hint": "Model totals cover local Codex session records available on this Mac.",
            "local_models_title": "Models on this Mac · all accounts",
            "local_models_hint": "Local session records do not contain a reliable account ID, so model totals are kept separate from per-account totals.",
            "automatic_warmup": "Experimental 5-hour Warmup",
            "warmup_time": "Daily time",
            "warmup_hint": "Off by default. At this local time, one real minimal request per saved account attempts to start an inactive work window and consumes a small amount of usage.",
            "warmup_attempting": "Warmup request in progress",
            "warmup_confirmed": "5-hour window observed",
            "warmup_unconfirmed": "Request sent; window unconfirmed",
            "warmup_failed": "Warmup failed",
            "language": "Language",
            "general": "General",
            "usage_and_alerts": "Usage & Alerts",
            "experimental": "Experimental",
            "system_default": "System Default",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "A browser window will open for Codex sign-in.",
            "sign_in_pending_hint": "Complete sign-in in the browser, or cancel here if you closed it.",
            "waiting_for_sign_in": "Waiting for browser sign-in",
            "no_accounts": "No saved accounts",
            "ok": "OK",
            "operation_failed": "Operation failed",
            "switch_failed": "Account switch failed",
            "active_unconfirmed": "Active account could not be confirmed",
            "identity_temporarily_unavailable": "Account verification is temporarily unavailable",
            "identity_mismatch": "The active sign-in does not match the saved current account",
            "retry": "Retry",
            "switched_reopen_title": "Account switched",
            "switched_reopen_message": "The selected account is active, but Codex Desktop could not be reopened. Open Codex manually to continue.",
        ],
        .simplifiedChinese: [
            "usage": "用量",
            "five_hour": "5 小时",
            "weekly": "周额度",
            "usage_unavailable": "用量暂不可用",
            "left": "% 剩余",
            "resets": "重置于",
            "manage": "管理账号",
            "settings": "设置",
            "quit": "退出应用",
            "switch_title": "切换到 %@？",
            "confirm_switch": "确认切换",
            "switch_body": "Codex Desktop 将关闭并重新打开。正在运行的 Desktop 任务可能中断。现有 CLI 会话保持运行，新 CLI 会话将使用所选账号。",
            "switch_impact_desktop": "正在运行的 Desktop 任务可能中断",
            "switch_impact_existing_cli": "已经打开的 CLI 会话保持原账号",
            "switch_impact_new_cli": "新开的 CLI 会话使用所选账号",
            "switching_title": "正在切换账号…",
            "cancel": "取消",
            "switch": "切换账号",
            "accounts": "账号",
            "back": "返回",
            "add_account": "添加账号",
            "cancel_add_account": "取消添加账号",
            "remove": "移除",
            "remove_account": "移除账号",
            "active": "当前",
            "remove_title": "移除 %@？",
            "remove_body": "此操作只会移除这台 Mac 上保存的本地账号档案。",
            "launch_at_login": "登录时自动启动",
            "launch_at_login_requires_approval": "需要在系统设置中允许此登录项。",
            "launch_at_login_unavailable": "macOS 找不到此登录项。",
            "open_system_settings": "打开系统设置",
            "show_menu_bar_percentage": "在菜单栏显示百分比",
            "show_five_hour_usage": "显示 5 小时用量",
            "show_supported_five_hour_usage": "支持的账号显示 5 小时额度",
            "account_name_style": "账号名称",
            "show_email": "邮箱",
            "show_nickname": "昵称",
            "show_nickname_and_email": "昵称 + 邮箱",
            "edit_nickname": "编辑备注",
            "set_remark": "设置备注",
            "nickname": "备注名称",
            "nickname_hint": "将显示在菜单栏和账号列表；留空时使用登录邮箱。",
            "save": "保存",
            "show_token_activity": "显示 Token 消耗统计",
            "show_token_activity_hint": "显示每个账号的今日消耗和底部合计。",
            "token_scanning": "正在统计本机 Token…",
            "token_scanning_short": "统计中…",
            "today_token": "今日 Token",
            "total_token_today": "今日 Token 合计",
            "token_unavailable_short": "暂无数据",
            "five_hour_reset_notifications": "5 小时额度恢复提醒",
            "five_hour_reset_notifications_hint": "提醒包含“切换到此账号”。检测到任务或无法确认空闲时，会先要求确认。",
            "notification_permission_denied": "通知权限未开启。请在系统设置中允许 Tiny Codex Switcher 发送通知。",
            "task_switch_active_title": "Codex 有正在运行的任务",
            "task_switch_active_body": "%@ 个运行中任务可能被中断。仍然切换吗？",
            "task_switch_unknown_title": "无法确认任务状态",
            "task_switch_unknown_body": "切换可能中断 Codex 任务。仍然切换吗？",
            "switch_anyway": "仍然切换",
            "switch_in_progress": "另一个账号操作正在进行，请完成后重试。",
            "five_hour_reset_notification_title": "5 小时额度已到重置时间",
            "five_hour_reset_notification_body": "%@ 的 5 小时额度预计已经恢复。",
            "notification_switch_action": "切换到此账号",
            "today": "今天",
            "last_7_days": "7 天",
            "last_30_days": "30 天",
            "local_model_usage_hint": "模型明细仅统计这台 Mac 上现存的 Codex 会话记录。",
            "local_models_title": "这台 Mac 的模型 · 全部账号",
            "local_models_hint": "本地会话记录缺少可靠的账号 ID，因此模型统计与单账号总量分开显示。",
            "automatic_warmup": "实验性 5 小时预热",
            "warmup_time": "每日时间",
            "warmup_hint": "默认关闭。到设定时间后，会为每个已保存账号发送一次真实的最小请求，尝试启动未活跃窗口，并会消耗少量用量。",
            "warmup_attempting": "正在发送预热请求",
            "warmup_confirmed": "已观察到 5 小时窗口",
            "warmup_unconfirmed": "已发送，窗口未确认",
            "warmup_failed": "预热失败",
            "language": "语言",
            "general": "常规",
            "usage_and_alerts": "用量与提醒",
            "experimental": "实验功能",
            "system_default": "跟随系统",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "将打开浏览器进行 Codex 登录。",
            "sign_in_pending_hint": "请在浏览器完成登录；如果已关闭页面，可在此取消。",
            "waiting_for_sign_in": "等待浏览器登录",
            "no_accounts": "暂无已保存账号",
            "ok": "好",
            "operation_failed": "操作失败",
            "switch_failed": "账号切换失败",
            "active_unconfirmed": "无法确认当前账号",
            "identity_temporarily_unavailable": "暂时无法校验当前账号",
            "identity_mismatch": "当前登录身份与保存的当前账号不一致",
            "retry": "重新验证",
            "switched_reopen_title": "账号已切换",
            "switched_reopen_message": "所选账号已经生效，但 Codex Desktop 未能重新打开。请手动打开 Codex 继续使用。",
        ],
    ]
}
