import Foundation

enum L10n {
    static func string(_ key: String, language: AppLanguage) -> String {
        let resolved: AppLanguage
        switch language {
        case .system:
            resolved = Locale.preferredLanguages.first?.hasPrefix("zh") == true
                ? .simplifiedChinese
                : .english
        case .english, .simplifiedChinese:
            resolved = language
        }
        return tables[resolved]?[key] ?? tables[.english]?[key] ?? key
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: [
            "usage": "Usage",
            "five_hour": "5h",
            "weekly": "7d",
            "usage_unavailable": "Usage unavailable",
            "left": "% left",
            "resets": "Resets",
            "manage": "Manage Accounts",
            "settings": "Settings",
            "quit": "Quit",
            "switch_title": "Switch to %@?",
            "switch_body": "Codex Desktop will close and reopen. A running Desktop task may be interrupted. Existing CLI sessions stay open; new CLI sessions use the selected account.",
            "cancel": "Cancel",
            "switch": "Switch Account",
            "accounts": "Accounts",
            "back": "Back",
            "add_account": "Add Account",
            "cancel_add_account": "Cancel Adding Account",
            "remove": "Remove",
            "active": "Active",
            "remove_title": "Remove %@?",
            "remove_body": "This removes only the saved local profile from this Mac.",
            "launch_at_login": "Launch at Login",
            "launch_at_login_requires_approval": "Approval is required in System Settings.",
            "launch_at_login_unavailable": "macOS could not find this Login Item.",
            "open_system_settings": "Open System Settings",
            "show_menu_bar_percentage": "Show Percentage in Menu Bar",
            "show_five_hour_usage": "Show 5-hour Usage",
            "account_name_style": "Account Name",
            "show_email": "Email",
            "show_nickname": "Nickname",
            "show_nickname_and_email": "Nickname + Email",
            "edit_nickname": "Edit Nickname",
            "nickname": "Nickname",
            "nickname_hint": "Leave blank to use the sign-in email.",
            "save": "Save",
            "show_token_activity": "Show Token Activity",
            "today": "Today",
            "last_7_days": "7d",
            "last_30_days": "30d",
            "local_model_usage_hint": "Model totals cover local Codex session records available on this Mac.",
            "local_models_title": "Models on this Mac · all accounts",
            "local_models_hint": "Local session records do not contain a reliable account ID, so model totals are kept separate from per-account totals.",
            "automatic_warmup": "Experimental 5-hour Warmup",
            "warmup_time": "Daily time",
            "warmup_hint": "Off by default. At this local time, one real minimal request per saved account attempts to start an inactive work window and consumes a small amount of usage.",
            "warmup_attempting": "Warmup request in progress",
            "warmup_confirmed": "5-hour window observed",
            "warmup_unconfirmed": "Request sent; window unconfirmed",
            "warmup_failed": "Warmup failed",
            "language": "Language",
            "system_default": "System Default",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "A browser window will open for Codex sign-in.",
            "sign_in_pending_hint": "Complete sign-in in the browser, or cancel here if you closed it.",
            "no_accounts": "No saved accounts",
            "ok": "OK",
            "operation_failed": "Operation failed",
            "switch_failed": "Account switch failed",
            "active_unconfirmed": "Active account could not be confirmed",
            "switched_reopen_title": "Account switched",
            "switched_reopen_message": "The selected account is active, but Codex Desktop could not be reopened. Open Codex manually to continue.",
        ],
        .simplifiedChinese: [
            "usage": "用量",
            "five_hour": "5 小时",
            "weekly": "7 天",
            "usage_unavailable": "用量暂不可用",
            "left": "% 剩余",
            "resets": "重置于",
            "manage": "管理账号",
            "settings": "设置",
            "quit": "退出应用",
            "switch_title": "切换到 %@？",
            "switch_body": "Codex Desktop 将关闭并重新打开。正在运行的 Desktop 任务可能中断。现有 CLI 会话保持运行，新 CLI 会话将使用所选账号。",
            "cancel": "取消",
            "switch": "切换账号",
            "accounts": "账号",
            "back": "返回",
            "add_account": "添加账号",
            "cancel_add_account": "取消添加账号",
            "remove": "移除",
            "active": "当前",
            "remove_title": "移除 %@？",
            "remove_body": "此操作只会移除这台 Mac 上保存的本地账号档案。",
            "launch_at_login": "登录时自动启动",
            "launch_at_login_requires_approval": "需要在系统设置中允许此登录项。",
            "launch_at_login_unavailable": "macOS 找不到此登录项。",
            "open_system_settings": "打开系统设置",
            "show_menu_bar_percentage": "在菜单栏显示百分比",
            "show_five_hour_usage": "显示 5 小时用量",
            "account_name_style": "账号名称",
            "show_email": "邮箱",
            "show_nickname": "昵称",
            "show_nickname_and_email": "昵称 + 邮箱",
            "edit_nickname": "编辑昵称",
            "nickname": "昵称",
            "nickname_hint": "留空时使用登录邮箱。",
            "save": "保存",
            "show_token_activity": "显示 Token 用量",
            "today": "今天",
            "last_7_days": "7 天",
            "last_30_days": "30 天",
            "local_model_usage_hint": "模型明细仅统计这台 Mac 上现存的 Codex 会话记录。",
            "local_models_title": "这台 Mac 的模型 · 全部账号",
            "local_models_hint": "本地会话记录缺少可靠的账号 ID，因此模型统计与单账号总量分开显示。",
            "automatic_warmup": "实验性 5 小时预热",
            "warmup_time": "每日时间",
            "warmup_hint": "默认关闭。到设定时间后，会为每个已保存账号发送一次真实的最小请求，尝试启动未活跃窗口，并会消耗少量用量。",
            "warmup_attempting": "正在发送预热请求",
            "warmup_confirmed": "已观察到 5 小时窗口",
            "warmup_unconfirmed": "已发送，窗口未确认",
            "warmup_failed": "预热失败",
            "language": "语言",
            "system_default": "跟随系统",
            "english": "English",
            "simplified_chinese": "简体中文",
            "sign_in_hint": "将打开浏览器进行 Codex 登录。",
            "sign_in_pending_hint": "请在浏览器完成登录；如果已关闭页面，可在此取消。",
            "no_accounts": "暂无已保存账号",
            "ok": "好",
            "operation_failed": "操作失败",
            "switch_failed": "账号切换失败",
            "active_unconfirmed": "无法确认当前账号",
            "switched_reopen_title": "账号已切换",
            "switched_reopen_message": "所选账号已经生效，但 Codex Desktop 未能重新打开。请手动打开 Codex 继续使用。",
        ],
    ]
}
